#!/bin/bash

set -e

PKGNAME=ppx_sexp

if [[ -z $(ocamlfind query $PKGNAME 2>&1 | grep "not found") ]]; then
    ocamlfind remove $PKGNAME
fi

ocamlbuild -package compiler-libs.common ppx_sexp.native

ocamlbuild ppxSexp.cma
ocamlbuild ppxSexp.cmxa

ocamlfind install $PKGNAME META \
    _build/ppx_sexp.native \
    _build/*.cmi _build/*.cma _build/*.cmxa _build/*.mli _build/*.ml
